# frozen_string_literal: true
ruby '3.3.6'

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "open-uri", "~> 0.3.0"
gem "mini_magick", "~> 4.12"
gem "aws-sdk-s3", "~> 1.132"
